#ifndef BOARD_MAPLEF103_H
#define BOARD_MAPLEF103_H
#ifdef BOARD_MAPLE

#define __HARDWARE_TIMER_2 2
#define __HARDWARE_TIMER_3 3

#define __DISABLE_DEBUG_PORT afio_cfg_debug_ports(AFIO_DEBUG_NONE)

#define __MODE_SELECT mode_select = 0x0F - (uint8_t)(((GPIOA->regs->IDR) >> 4) & 0x0F)

#define __TIMER2_BASE TIMER2_BASE
#define __TIMER3_BASE TIMER3_BASE

#define __TIMER_CH1 TIMER_CH1
#define __TIMER_CH2 TIMER_CH2

#define __TIMER2_CLEAR_COMP1 TIMER2_BASE->SR = 0x1E5F & ~TIMER_SR_CC1IF	// Clear Timer2/Comp1 interrupt flag
#define __TIMER2_CLEAR_COMP2 TIMER2_BASE->SR = 0x1E5F & ~TIMER_SR_CC2IF	// Clear Timer2/Comp2 interrupt flag

#define __TIMER_SR_CC1IF TIMER_SR_CC1IF
#define __TIMER_SR_CC2IF TIMER_SR_CC2IF

#define __TIMER2_CHECK_CC1IF TIMER2_BASE->SR & TIMER_SR_CC1IF

#define __TELEMETRY_RX_DISABLE USART3_BASE->CR1 &= ~ USART_CR1_RE	// Disable telemetry receive
#define __TELEMETRY_TX_DISABLE USART2_BASE->CR1 &= ~ USART_CR1_TE	// Disable telemetry transmit

#define __TELEMETRY_RX_INTERRUPT_DISABLE USART2_BASE->CR1 &= ~USART_CR1_RXNEIE;

#define __TELEMETRY_TX_INTERUPT_DISABLE USART3_BASE->CR1 &= ~USART_CR1_TXEIE
#define __TELEMETRY_TX_INTERUPT_ENABLE USART3_BASE->CR1 |= USART_CR1_TXEIE

#define OCR1A TIMER2_BASE->CCR1
#define TCNT1 TIMER2_BASE->CNT
#define TIFR1 TIMER2_BASE->SR
#define OCF1A_bm TIMER_SR_CC1IF
#define UDR0 USART2_BASE->DR
#define UCSR0B USART2_BASE->CR1
#define RXCIE0 USART_CR1_RXNEIE_BIT
#define TXCIE0 USART_CR1_TXEIE_BIT

#define __USART_CR1_PCE USART_CR1_PCE_BIT

#endif // BOARD_MAPLE
#endif // !BOARD_MAPLEF103_H
